<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="Raghav_Global" failures="1" tests="4" name="Sanity Test Execution" time="9.076" errors="0" timestamp="2025-09-12T10:57:26 IST">
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="2.27">
    <failure type="java.lang.AssertionError" message="User not found after creation! expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: User not found after creation! expected [200] but found [404]
at api.test.UserTests.testGetUserByName(UserTests.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests" name="testUpdateUser" time="1.855"/>
  <testcase classname="api.test.UserTests2" name="testGetAllUsers" time="2.262"/>
  <testcase classname="api.test.UserTests2" name="testUpdateUser" time="2.677"/>
  <testcase classname="api.test.UserTests" name="testCreateUser" time="0.0">
    <ignored/>
  </testcase> <!-- testCreateUser -->
  <testcase classname="api.test.UserTests2" name="testCreateMultipleUsers" time="0.0">
    <ignored/>
  </testcase> <!-- testCreateMultipleUsers -->
  <testcase classname="api.test.UserTests2" name="testDeleteUser" time="0.0">
    <ignored/>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.test.DDTests" name="testPostUser" time="0.0">
    <ignored/>
  </testcase> <!-- testPostUser -->
  <testcase classname="api.test.DDTests" name="deleteAllUsers" time="0.0">
    <ignored/>
  </testcase> <!-- deleteAllUsers -->
  <testcase classname="api.test.UserTests" name="testDeleteUser" time="0.0">
    <ignored/>
  </testcase> <!-- testDeleteUser -->
</testsuite> <!-- Sanity Test Execution -->
